version: '3.5'

services:

# mysql service 
    mysql:
        image: mysql:5.7.17
        restart: always
        env_file:
          - ./.env
        container_name: mysqldb  
        ports: 
          - "4306:3306"  
        volumes:
          - db_data:/var/lib/mysql"
        networks:
          safeschool_network:
            aliases:
              - mysql

# apache service
    #apache:
        #image: httpd:2.4
        #ports:
          #- "81:80"
        #restart: always
        #volumes:
          #- "./volumes/apache2/logs:/var/log/apache2/"
        #links:
            #- php
        #networks:
          #crv_dev_network:
            #aliases:
              #- apache

# apache + php service
    apache_php:
        image: php:5.6-apache
        restart: always
        build: ./php-5.6-apache
        container_name: webserver
        ports:
          - "8800:80"
        env_file:
          - ./.env

        volumes:
          - "./volumes/php/app/cache:/var/www/html/safeSchool/app/cache/:rw"
          - "./volumes/php/app/logs:/var/www/html/safeSchool/app/logs/:rw"
          - "./volumes/.composer:/var/www/.composer"
          - "./php-5.6-apache/php.ini:/usr/local/etc/php/php.ini"          #- "./custom-script.sh:/usr/local/bin/custom-script.sh"
          - "./app/safeSchool:/var/www/html/safeSchool"
        #command:
          #- custom-script.sh 
        links:
          - mysql  
        networks:
          safeschool_network:
            aliases:
              - apache_php

# phpmyadmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: php_your_admin
        ports:
          - "8100:80"
        restart: always  
        #env_file:
          #- ./.env  
        environment:
          PMA_HOST: mysql
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root_dbpassword 
        links:
          - mysql   
        networks:
          safeschool_network:
            aliases:
              - phpmyadmin        

volumes:
  db_data: {}

networks:
  safeschool_network:
    driver: bridge
